<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jasa Pasang Plafon Gypsum</name>
   <tag></tag>
   <elementGuidId>9bbde62b-8f43-4c06-92d9-865bfe707050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-item-3179 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-3179']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5b13405-19c8-4f6d-b694-2cbb23c8561a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kanggo.id/layanan-kanggo/layanan-perbaikan-plafon/</value>
      <webElementGuid>78f85b5f-b8c0-4cee-8f02-33c4a2d31e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jasa Pasang Plafon Gypsum</value>
      <webElementGuid>a0d1d87a-81bd-4525-b873-144a24d72a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-3179&quot;)/a[1]</value>
      <webElementGuid>45c4a5fc-0e45-4a96-a8d2-8e75ae8b90cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-3179']/a</value>
      <webElementGuid>f1fd3dca-2e69-4697-af4d-9bad78cb6b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Jasa Pasang Plafon Gypsum')]</value>
      <webElementGuid>2bdd7a7f-b6af-4718-9a25-aa890329f442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa Pipa Mampet &amp; Instalasi Pipa'])[1]/following::a[1]</value>
      <webElementGuid>99e68d86-cbff-4419-a341-3309d1312a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan'])[1]/following::a[2]</value>
      <webElementGuid>849d4899-d3ac-4cc2-9142-1022c337c982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa Pasang Pintu &amp; Perbaikan'])[1]/preceding::a[1]</value>
      <webElementGuid>fa81463b-ea64-41c8-8945-cca28ea8dcee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa Pasang Keramik'])[1]/preceding::a[2]</value>
      <webElementGuid>aa3c15c9-4968-41b1-862b-f772d249cc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jasa Pasang Plafon Gypsum']/parent::*</value>
      <webElementGuid>b21d7e0c-e85a-4f02-9a6d-ff754bf78082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kanggo.id/layanan-kanggo/layanan-perbaikan-plafon/')]</value>
      <webElementGuid>d48c4500-3c92-4dfa-b90f-1101e6332b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>82a2c9f6-3d99-47d4-b9b4-50aba450157a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kanggo.id/layanan-kanggo/layanan-perbaikan-plafon/' and (text() = 'Jasa Pasang Plafon Gypsum' or . = 'Jasa Pasang Plafon Gypsum')]</value>
      <webElementGuid>6d53c7f6-2f48-44cc-96c7-6a317d858ef0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
